//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentalIndividualField
    {
        public int Id { get; set; }
        public bool IsRequired { get; set; }
        public bool IsBar { get; set; }
        public Nullable<int> FKSubCategory_Id { get; set; }
        public int FkIndividualField_Id { get; set; }
        public int FKCategory_Id { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual IndividualField IndividualField { get; set; }
        public virtual SubCategory SubCategory { get; set; }
    }
}
