//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubMenu
    {
        public int Id { get; set; }
        public int OrderNumber { get; set; }
        public string ClassIcon { get; set; }
        public int FkMenu_Id { get; set; }
        public int FKPage_Id { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Page Page { get; set; }
    }
}
