Token = {
    'ICantCallToServer': null,
    'Error': null,
    'Success':null,
    'OrSomeErrorInServer':null,
    'NoDataForSave': null,
    'Showing':null,
    'Of':null,
    'CanNotDublicatedLanguage':null,
    'boolTrue': null,
    'boolFalse':null,
    'NoDataMore': null,
    'UserNotFound': null,
    'CanNotDublicatedRole': null,
    'InvalidDate': null,
    'ErrorConfirmPassword': null,
    'YouNotAllowedShowThisNotify': null,
    'ProductNotFound': null,
    'ICanNotLoadProductsBecuseThisAuctionIsStarted': null,
    'StartDateTimeMustBeMoreTthanOrEqualCurrent': null,
    'EndDateTimeMustBeMoreThanStartDateTime':null,
    'For':null,
'Product':null,
    'ProductNotFound':null,
    'Info':null,
    'ErrorDuplicate': null,
    'CanNotImportMore':null,
    "disActive": null,
    "active": null,
    "All": langIsEn?"All":"الكل"

};
