//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdDirectFieldDetail
    {
        public int AdId { get; set; }
        public Nullable<int> FKArea_Id { get; set; }
        public Nullable<int> FKSize_Id { get; set; }
        public Nullable<int> FKLocation_Id { get; set; }
        public Nullable<int> FKMatrial_Id { get; set; }
        public Nullable<int> FKNationality_Id { get; set; }
        public Nullable<int> FKMark_Id { get; set; }
        public Nullable<int> FkCountry_Id { get; set; }
        public Nullable<int> FkProvince_Id { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Nationality Nationality { get; set; }
        public virtual Size Size { get; set; }
        public virtual Location Location { get; set; }
        public virtual Ad Ad { get; set; }
        public virtual Area Area { get; set; }
        public virtual Country Country { get; set; }
        public virtual Mark Mark { get; set; }
        public virtual Province Province { get; set; }
    }
}
