//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdGroupsDetail
    {
        public int Id { get; set; }
        public int FKGroup_Id { get; set; }
        public bool IsCustomValue { get; set; }
        public string CustomValue { get; set; }
        public Nullable<int> FKGroupItem_Id { get; set; }
        public int FKAd_Id { get; set; }
    
        public virtual Ad Ad { get; set; }
        public virtual Group Group { get; set; }
        public virtual GroupsItem GroupsItem { get; set; }
    }
}
