//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyOffice
    {
        public int Id { get; set; }
        public long FKCompany_Id { get; set; }
        public int FKAddress_Id { get; set; }
        public int FKLocation_Id { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Company Company { get; set; }
        public virtual Location Location { get; set; }
    }
}
