//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndividualField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IndividualField()
        {
            this.AdIndividualFieldsDetails = new HashSet<AdIndividualFieldsDetail>();
            this.RentalIndividualFields = new HashSet<RentalIndividualField>();
        }
    
        public int Id { get; set; }
        public string ResourcesName { get; set; }
        public int FKInputType_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdIndividualFieldsDetail> AdIndividualFieldsDetails { get; set; }
        public virtual InputsType InputsType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentalIndividualField> RentalIndividualFields { get; set; }
    }
}
