//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Notification()
        {
            this.UsersPrivateNotifies = new HashSet<UsersPrivateNotify>();
        }
    
        public long Id { get; set; }
        public string TitleAr { get; set; }
        public string TitleEn { get; set; }
        public System.DateTime DataTime { get; set; }
        public bool IsAlsoToAdmin { get; set; }
        public string BodyAr { get; set; }
        public string BodyEn { get; set; }
        public Nullable<int> FkPage_Id { get; set; }
        public Nullable<int> TargetId { get; set; }
    
        public virtual Page Page { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersPrivateNotify> UsersPrivateNotifies { get; set; }
    }
}
