//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.AdComments = new HashSet<AdComment>();
            this.AdFavorites = new HashSet<AdFavorite>();
            this.Ads = new HashSet<Ad>();
            this.ChatMessages = new HashSet<ChatMessage>();
            this.PagesRoles = new HashSet<PagesRole>();
            this.UserLogins = new HashSet<UserLogin>();
            this.UserRoles = new HashSet<UserRole>();
            this.UsersPrivateNotifies = new HashSet<UsersPrivateNotify>();
        }
    
        public long Id { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public bool IsBlocked { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string FullName { get; set; }
        public Nullable<int> FkImage_Id { get; set; }
        public int FKAddress_Id { get; set; }
        public Nullable<int> FKGender_Id { get; set; }
        public int FKLanguage_Id { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> PhoneActiveCode { get; set; }
        public Nullable<bool> IsPhoneActivated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdComment> AdComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdFavorite> AdFavorites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ad> Ads { get; set; }
        public virtual Address Address { get; set; }
        public virtual AllFile AllFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatMessage> ChatMessages { get; set; }
        public virtual Company Company { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual LanguageType LanguageType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagesRole> PagesRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLogin> UserLogins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRole> UserRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersPrivateNotify> UsersPrivateNotifies { get; set; }
    }
}
